# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

[package]
name = "wasmvmhost"
description = "Wasm host interface for WasmLib"
license = "Apache-2.0"
version = "1.0.1"
authors = ["Eric Hop <eric@iota.org>"]
edition = "2021"
repository = "https://github.com/nnikolash/wasp-types-exported"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.92"
wasmlib = { path = "../wasmlib" }
#wasmlib = { git = "https://github.com/nnikolash/wasp-types-exported/packages/wasmvm/wasmlib", branch = "develop" }

[dev-dependencies]
wasm-bindgen-test = "0.3.42"
