name: Build and upload API docs

on:
  release:
    types: [published]

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  actions: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/evm/docs-generator
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4

      - name: Get release version
        id: get_release_version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's/.*v\([0-9]*\.[0-9]*\).*/\1/')
          echo VERSION=$VERSION >> $GITHUB_OUTPUT
      
      - name: Build reference docs
        run: |
          yarn && yarn gen-docs:all

      - name: Compress generated docs
        run: |
          tar czvf iscmagic.tar.gz docs/iscmagic/*
          tar czvf iscutils.tar.gz docs/iscutils/*

      - name: Upload docs to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_IOTA_WIKI }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_IOTA_WIKI }}
          AWS_DEFAULT_REGION: "eu-central-1"
        run: |
          aws s3 cp iscmagic.tar.gz s3://files.iota.org/iota-wiki/wasp/${{ steps.get_release_version.outputs.VERSION }}/ --acl public-read
          aws s3 cp iscutils.tar.gz s3://files.iota.org/iota-wiki/wasp/${{ steps.get_release_version.outputs.VERSION }}/ --acl public-read